name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyspark-version: ["2.4.7", "3.0.0", "3.0.2", "3.1.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: |
          pip install scikit-learn pyspark==${{ matrix.pyspark-version }}
      - run: |
          python one_vs_rest.py
